CREATE TABLE pengingat (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tipe VARCHAR(255) NOT NULL,
    pesan TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    clicked_at TIMESTAMP NULL
);

CREATE TABLE pengingat_terjadwal ( id INT AUTO_INCREMENT PRIMARY KEY, setiap int DEFAULT 3, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP );
INSERT INTO `pengingat_terjadwal` (`id`, `setiap`, `created_at`, `updated_at`) VALUES (NULL, '3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);